# Generated by Django 3.2 on 2022-06-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0004_category_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EntryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=10, null=True)),
                ('option', models.CharField(max_length=10, null=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mcl.topic')),
            ],
        ),
    ]
