# Generated by Django 3.2 on 2022-06-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0005_entrylist_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='dist',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
