# Generated by Django 3.2 on 2022-06-27 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0006_auto_20220627_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrylist',
            options={'verbose_name': 'Entry List', 'verbose_name_plural': 'Entry Lists'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mcl.shop'),
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=10, null=True)),
                ('entry_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mcl.entrylist')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mcl.topic')),
            ],
            options={
                'verbose_name': 'Check List',
                'verbose_name_plural': 'Check Lists',
            },
        ),
    ]
