# Generated by Django 3.2 on 2022-06-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0007_auto_20220627_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='point_cat',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
