# Generated by Django 3.2 on 2022-06-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0008_checklist_point_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='points',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='entrylist',
            old_name='points',
            new_name='point',
        ),
    ]
