# Generated by Django 3.2 on 2022-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0009_auto_20220627_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
