# Generated by Django 3.2 on 2022-06-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0010_shop_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Site',
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.RenameField(
            model_name='entrylist',
            old_name='shop',
            new_name='site',
        ),
    ]
