# Generated by Django 3.2 on 2022-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0011_auto_20220628_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
