# Generated by Django 3.2 on 2022-06-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0017_rename_comment_entrylist_cust_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylist',
            name='comment_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_one', to='mcl.comment'),
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='comment_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_three', to='mcl.comment'),
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='comment_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_two', to='mcl.comment'),
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='cust_comm',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Custom Comment'),
        ),
    ]
