# Generated by Django 3.2 on 2022-07-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0020_sitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='dist',
            new_name='district',
        ),
        migrations.AddField(
            model_name='site',
            name='area',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
