# Generated by Django 3.2 on 2022-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0021_auto_20220703_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='manager_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
