# Generated by Django 3.2 on 2022-07-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0022_site_manager_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='status',
            new_name='is_active',
        ),
    ]
