# Generated by Django 3.2 on 2022-07-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0023_auto_20220705_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg. CENTRAL-A', max_length=100, null=True, unique=True, verbose_name='Area Name')),
                ('code', models.CharField(help_text='eg. CA', max_length=50, null=True, unique=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('manager', models.CharField(max_length=250, null=True, verbose_name='Area Manager Name')),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.RemoveField(
            model_name='site',
            name='area',
        ),
        migrations.RemoveField(
            model_name='site',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='site',
            name='manager',
            field=models.CharField(max_length=200, null=True, verbose_name='Site Manager Name'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg. DISTRICT-01', max_length=100, null=True, unique=True, verbose_name='District Name')),
                ('code', models.CharField(help_text='eg. 01', max_length=50, null=True, unique=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('manager', models.CharField(max_length=250, null=True, verbose_name='District Manager Name')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mcl.area')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mcl.district'),
        ),
    ]
