# Generated by Django 3.2 on 2022-07-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0024_auto_20220717_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='code',
        ),
    ]
