# Generated by Django 3.2 on 2022-07-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0025_remove_area_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='name',
        ),
    ]
