# Generated by Django 3.2 on 2022-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0028_auto_20220721_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone No'),
        ),
    ]
