# Generated by Django 3.2 on 2022-07-21 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcl', '0030_auto_20220721_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_manager', to=settings.AUTH_USER_MODEL, verbose_name='Area Manager'),
        ),
        migrations.AlterField(
            model_name='district',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_manager', to=settings.AUTH_USER_MODEL, verbose_name='District Manager'),
        ),
        migrations.AlterField(
            model_name='site',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_manager', to=settings.AUTH_USER_MODEL, verbose_name='Site Manager'),
        ),
    ]
