# Generated by Django 3.2 on 2022-07-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0032_userproxydetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProxyDetail',
        ),
    ]
