# Generated by Django 3.2 on 2022-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0033_delete_userproxydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(max_length=20, verbose_name='Employee ID'),
        ),
    ]
