# Generated by Django 3.2 on 2022-07-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0036_alter_profile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='entry_last_date',
            field=models.PositiveIntegerField(help_text='eg. 10', null=True, verbose_name='Last Entry Date for BM'),
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='otp',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
