# Generated by Django 3.2 on 2022-07-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0037_auto_20220731_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylist',
            name='otp',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
