# Generated by Django 3.2 on 2022-09-05 09:56

from django.db import migrations, models
import django.db.models.deletion
import mcl.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0038_alter_entrylist_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to=mcl.models.EntryImage.file_dir)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryimage', to='mcl.entrylist')),
            ],
        ),
    ]
