# Generated by Django 3.2 on 2022-09-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0039_entryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryimage',
            old_name='file',
            new_name='image',
        ),
    ]
