# Generated by Django 3.2 on 2022-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0040_rename_file_entryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylist',
            name='otp',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
