# Generated by Django 3.2 on 2022-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0045_alter_entryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylist',
            name='comment_one',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment One'),
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='comment_three',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment Three'),
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='comment_two',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment Two'),
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='cust_comm',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Custom Comment'),
        ),
    ]
