# Generated by Django 3.2 on 2023-06-20 12:55

from django.db import migrations, models
import mcl.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0046_auto_20220906_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='topic_image',
            field=models.ImageField(blank=True, null=True, upload_to=mcl.models.CheckList.image_dir),
        ),
    ]
