# Generated by Django 3.2 on 2023-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0047_checklist_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylist',
            name='rem_comm',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Remarks Comment'),
        ),
    ]
