# Generated by Django 3.2 on 2023-07-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcl', '0049_entrylist_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrylist',
            name='current_user',
        ),
    ]
